a_qconfig:
    quantizer: LSQFakeQuantize
    observer: AvgMSEFastObserver
    bit: 4
    symmetric: False
    ch_axis: -1
w_qconfig:
    quantizer: AdaRoundFakeQuantize
    observer: MSEObserver
    bit: 2
    symmetric: False
    ch_axis: 0
calibrate: 256
recon:
    batch_size: 2
    scale_lr: 4.0e-5
    warm_up: 0.2
    weight: 0.01
    iters: 20000
    b_range: [20, 2]
    keep_gpu: True
    round_mode: learned_hard_sigmoid
    drop_prob: 0.5
